declare function doPaging(e: any): number;
declare function setNextLastEnable(id: any, setDisable: any): void;
declare function setFirstPreviousEnable(id: any, setDisable: any): void;
declare function SubmitTextBoxValue(editingContext: any, path: any, element: any, callback: any, ignoreScriptTags: any): void;
declare function SubmitCalendarEditorValue(editingContext: any, path: any, IsDate: any, IsNullable: any, dateValue: any, prevValue: any, successCallback: any): void;
declare function SubmitRichTextBoxValue(editingContext: any, path: any, element: any, callback: any): void;
declare function parseDate(input: any): Date;
declare function parseTime(input: any): Date;
declare function parseDateTimeISO(date: any): Date;
declare function SubmitDropDownValue(editingContext: any, path: any, element: any): void;
declare function SubmitDropDownValueCommon(editingContext: any, path: any, selectedValue: any, element: any, callbackfunction: any): void;
declare function SetContextProviderValueSync(editingContext: any, path: any, dataPair: any, element: any): void;
declare function SetDynamicContextProviderValue(editingContext: any, path: any, dataPair: any): void;
declare function SetValueArrayEditor(editingContext: any, selectedPath: any, selectedIndex: any, type: any): void;
declare function SkipRootFolders(element: any): boolean;
declare function UpdateValidationReasons(eventData: any, editingContextId: any): void;
declare function updateGlobalValidations(validationIssues: any, element: any): void;
declare function resizeOpenUrlView(e: any): void;
declare function DisposeActionBarView(controlid: any): void;
declare function resizeCSVEditor(e: any): void;
declare function ClearControlDataCache(id: any): void;
declare function ResizeMergeTextPickerEditor(uniqueId: any, info: any): void;
declare function resizeSilverButton(e: any): void;
declare function resizeSilverTextBlockView(e: any): void;
declare function SimpleControlResize(e: any): void;
declare function resizeSilverRichTextBox(e: any): void;
declare function ResizeSaveButtonPart(e: any): void;
declare function resizeSilverCheckBoxView(e: any): void;
declare function resizeSilverToggleButton(e: any): void;
declare function ResizeSilverPropertyGridRoot(e: any): void;
declare function ResizeNavigationTreeContainer(e: any): void;
declare function resizeLoadedAssembly(elementId: any, extraInfo: any): void;
declare function resizeStartUpAssignment(elementId: any, extraInfo: any): void;
declare function resizeChatPart(e: any): void;
declare function ResizeChatUsingSplitter(componentId: any): void;
declare function resizeAddCommentPart(options: any, isFistime: any, isMobileRequest: any): void;
declare function onSuccessAddComment(instanceId: any): void;
declare function OnBeginSubmissionOfAddComment(instanceId: any, e: any): boolean;
declare function resizeAddDocumentPart(options: any, isFirstTime: any): void;
declare function OnSuccesAddDocument(instanceId: any): void;
declare function OnBeginSubmissionOfAddDocument(instanceId: any, e: any): boolean;
declare function OpenActionAndDescriptionForAddDocument(instanceId: any, elem: any): void;
declare function ResizeCkEditorIfNotLoaded(paramenter: any): void;
declare function DisplayTime(): void;
declare function ShowMenuForNotificationsPart(elem: any): void;
declare function ResizeSelectEntityPickerEditor(uniqueId: any, info: any): void;
declare function EntityPickerResize(elem: any, newWidth: any, newHeight: any): void;
declare function EntityPickerScrollResize(entityPickerControlData: any, newWidth: any): void;
declare function ResizeImageInfoEditor(uniqueId: any, info: any): void;
declare function ToggleScrollingArrowForImageInfoEditor(info: any): boolean;
declare function ImageInfoLeftArrowClick(elemClicked: any): void;
declare function ImageInfoRightArrowClick(elemClicked: any): void;
declare function AdjustImageInfoEditorTabPos(tabElem: any): void;
declare function InitializeFolderDataTextBoxPart(controlElem: any, dataName: any, folderId: any): void;
declare function InitializeFolderDataRichTextBoxPart(controlElem: any, dataName: any, folderId: any): void;
declare function InitializeNotificationsPart(controlElem: any, excludeNotificationTypes: any, folderId: any, id: any): void;
declare function SendNotification(listOfNotify: any, id: any, controlElem: any): void;
declare function ServiceCatalogFolderChangeEventHandler(componentId: any, eventData: any): void;
declare var MultiFileUploadData: any[];
declare function DisposeUploadedFileData(key: any): void;
declare function GetIPrintExportElements(): {};
declare function ComboEditorValueChanged(nodeInfo: any): void;
declare function CommonComboDispose(id: any): void;
declare function resizeSilverCaptureImagePanel(e: any): void;
declare function SilverCaptureImagePanelDisposed(instanceId: any): void;
declare function SaveButtonOnFolderDataChanged(controlId: any, folderId: any, eventData: any): void;
declare function resizeFolderDataRichTextBoxPart(e: any): void;
declare function resizeSelectMultipleEntityActionContainer(instanceId: any, parameters: any): void;
declare function resizeScratchPadPart(e: any): void;
declare function arrayBufferToBase64(buffer: any): string;
declare function InitializeTagsOnDesigner(instanceid: any): void;
/**
 * Copyright Decisions 2016. For License or Copyright information please contact support@decisions.com
*/
